from app.email.config import EmailConfigurationError, EmailSettings, load_email_settings
from app.email.provider import (
    BACKEND_TRANSACTIONAL_EMAIL_TYPES,
    MARKETING_EMAIL_TYPES,
    SUPABASE_AUTH_EMAIL_TYPES,
    EmailProvider,
    EmailSendRequest,
    EmailSendResult,
    EmailValidationError,
    normalize_safe_metadata,
    validate_recipient_email,
)
from app.email.service import EmailService, build_email_service
from app.email.event_store import (
    EVENT_STATUSES,
    OutboundEmailEventClaim,
    OutboundEmailEventClient,
    OutboundEmailEventConflictError,
    OutboundEmailEventError,
    OutboundEmailEventRecord,
    OutboundEmailEventRequest,
    OutboundEmailEventService,
    OutboundEmailEventValidationError,
    OutboundEmailEventNotFoundError,
    RECONCILIATION_OUTCOMES,
    SupabaseOutboundEmailEventClient,
    build_outbound_email_event_service,
)

__all__ = [
    "BACKEND_TRANSACTIONAL_EMAIL_TYPES",
    "EmailConfigurationError",
    "EmailProvider",
    "EmailSendRequest",
    "EmailSendResult",
    "EmailService",
    "EmailSettings",
    "EmailValidationError",
    "MARKETING_EMAIL_TYPES",
    "SUPABASE_AUTH_EMAIL_TYPES",
    "build_email_service",
    "load_email_settings",
    "normalize_safe_metadata",
    "validate_recipient_email",
    "EVENT_STATUSES",
    "OutboundEmailEventClaim",
    "OutboundEmailEventClient",
    "OutboundEmailEventConflictError",
    "OutboundEmailEventError",
    "OutboundEmailEventNotFoundError",
    "OutboundEmailEventRecord",
    "OutboundEmailEventRequest",
    "OutboundEmailEventService",
    "OutboundEmailEventValidationError",
    "RECONCILIATION_OUTCOMES",
    "SupabaseOutboundEmailEventClient",
    "build_outbound_email_event_service",
]
