import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'
import { DESKTOP_AUTH_STATUSES, getDesktopAuthViewModel } from './desktop_auth_ui.js'

const startupSource = readFileSync(new URL('./components/StartupLoginScreen.jsx', import.meta.url), 'utf8')
const startupChoiceSource = readFileSync(new URL('./components/StartupSessionChoiceScreen.jsx', import.meta.url), 'utf8')
const startupSetupSource = readFileSync(new URL('./components/StartupSessionSetupScreen.jsx', import.meta.url), 'utf8')
const diagnosticsSource = readFileSync(new URL('./components/MainDiagnosticsWindow.jsx', import.meta.url), 'utf8')
const appSource = readFileSync(new URL('./App.jsx', import.meta.url), 'utf8')
const cssSource = readFileSync(new URL('./styles/glass.css', import.meta.url), 'utf8')
const mainSource = readFileSync(new URL('../electron/main.cjs', import.meta.url), 'utf8')
const preloadSource = readFileSync(new URL('../electron/preload.cjs', import.meta.url), 'utf8')
const sessionSource = readFileSync(new URL('../electron/desktop_auth_session.cjs', import.meta.url), 'utf8')
const sensitivePattern = new RegExp([
  ['access', 'token'].join('_'),
  ['refresh', 'token'].join('_'),
  ['service', 'role'].join('_'),
  'Author' + 'ization',
].join('|'))

test('startup login screen renders for signed-out and token-expired states', () => {
  const visibleStatuses = new Set([
    DESKTOP_AUTH_STATUSES.SIGNED_OUT,
    DESKTOP_AUTH_STATUSES.TOKEN_EXPIRED,
    DESKTOP_AUTH_STATUSES.SIGNING_IN,
  ])

  assert.equal(visibleStatuses.has(getDesktopAuthViewModel({ status: 'signed-out' }).status), true)
  assert.equal(visibleStatuses.has(getDesktopAuthViewModel({ status: 'token-expired' }).status), true)
  assert.equal(visibleStatuses.has(getDesktopAuthViewModel({ status: 'signing-in' }).status), true)
  assert.equal(visibleStatuses.has(getDesktopAuthViewModel({ status: 'connected' }).status), false)
  assert.match(startupSource, /const LOGIN_VISIBLE_STATUSES = new Set/)
  assert.match(startupSource, /DESKTOP_AUTH_STATUSES\.SIGNED_OUT/)
  assert.match(startupSource, /DESKTOP_AUTH_STATUSES\.TOKEN_EXPIRED/)
  assert.match(startupSource, /if \(!shouldShowStartupLogin\(nextState\)\)/)
})

test('startup login screen uses mascot asset in header and center positions', () => {
  assert.match(startupSource, /import mascotUrl from '\.\.\/assets\/intervu-mascot\.svg'/)
  assert.match(startupSource, /startup-login-brand__mascot-frame/)
  assert.match(startupSource, /startup-login-mascot"/)
  assert.match(cssSource, /\.startup-login-brand__mascot-frame,[\s\S]*?\.startup-login-mascot-frame\s*{[\s\S]*?overflow: hidden;/)
  assert.match(cssSource, /\.startup-login-brand__mascot-frame\s*{[\s\S]*?width: 24px;[\s\S]*?height: 24px;/)
  assert.match(cssSource, /\.startup-login-mascot-frame\s*{[\s\S]*?width: 150px;[\s\S]*?height: 100px;/)
  assert.match(cssSource, /\.startup-login-mascot\s*{[\s\S]*?width: 150px;[\s\S]*?height: 100px;/)
})

test('startup login button uses safe preload auth login method and guards duplicate clicks', () => {
  assert.match(startupSource, /saiiaApi\?\.startAuthLogin/)
  assert.match(startupSource, /await saiiaApi\.startAuthLogin\(\)/)
  assert.match(startupSource, /saiiaApi\?\.getCloudStartupContext/)
  assert.match(startupSource, /window\.setInterval/)
  assert.match(startupSource, /if \(loginPending \|\| typeof saiiaApi\?\.startAuthLogin !== 'function'\)/)
  assert.match(startupSource, /disabled={loginPending \|\| authState\.loginDisabled}/)
  assert.doesNotMatch(startupSource, /completeStartup\?\.\(\)/)
  assert.doesNotMatch(startupSource, /supabase/i)
  assert.doesNotMatch(startupSource, /fetch\(/)
})

test('startup login reports desktop auth configuration failures safely', () => {
  const configError = 'Desktop cloud auth is not configured. Set SUPABASE_URL or VITE_SUPABASE_URL, SUPABASE_ANON_KEY or VITE_SUPABASE_ANON_KEY, and SAIIA_WEB_AUTH_URL or VITE_SAIIA_WEB_AUTH_URL in the environment that launches Electron.'
  const model = getDesktopAuthViewModel({
    status: DESKTOP_AUTH_STATUSES.SIGNED_OUT,
    error: configError,
    user_id: 'stale-user',
    email: 'stale@example.test',
  })

  assert.equal(model.status, DESKTOP_AUTH_STATUSES.SIGNED_OUT)
  assert.equal(model.detail, configError)
  assert.equal(model.email, null)
  assert.match(startupSource, /const errorDetail = authState\.error \|\| ''/)
  assert.match(startupSource, /const errorText = getStartupErrorMessage\(errorDetail\)/)
  assert.match(startupSource, /return 'Desktop auth is not configured\.'/)
  assert.match(startupSource, /const subtitle = 'Sign in to continue to your Intervu AI workspace\.'/)
})

test('desktop auth config requires Supabase URL, anon key, and website handoff URL in Electron main env', () => {
  assert.match(mainSource, /const DESKTOP_AUTH_ENV_KEYS = new Set\(\[/)
  assert.match(mainSource, /path\.join\(repoRoot, '\.env'\)/)
  assert.match(mainSource, /path\.join\(frontendRoot, '\.env\.local'\)/)
  assert.match(mainSource, /path\.join\(frontendRoot, '\.env'\)/)
  assert.match(mainSource, /Object\.prototype\.hasOwnProperty\.call\(process\.env, key\)/)
  assert.match(mainSource, /if \(!DESKTOP_AUTH_ENV_KEYS\.has\(key\)\) {[\s\S]*?return/)
  assert.doesNotMatch(mainSource, /SUPABASE_SERVICE_ROLE_KEY/)
  assert.doesNotMatch(mainSource, /GOOGLE_CLIENT_SECRET/)
  assert.match(mainSource, /process\.env\.SUPABASE_URL \|\| process\.env\.VITE_SUPABASE_URL/)
  assert.match(mainSource, /process\.env\.SUPABASE_ANON_KEY \|\| process\.env\.VITE_SUPABASE_ANON_KEY/)
  assert.match(mainSource, /process\.env\.SAIIA_WEB_AUTH_URL \|\| process\.env\.VITE_SAIIA_WEB_AUTH_URL/)
  assert.doesNotMatch(mainSource, /SAIIA_DESKTOP_AUTH_PROVIDER|VITE_SUPABASE_DESKTOP_AUTH_PROVIDER/)
  assert.match(sessionSource, /!this\.supabaseUrl \|\| !this\.supabaseAnonKey \|\| !this\.webAuthUrl/)
  assert.match(sessionSource, /\['http:', 'https:'\]\.includes\(authUrl\.protocol\)/)
  assert.match(sessionSource, /MISSING_DESKTOP_AUTH_CONFIG_MESSAGE/)
  assert.match(sessionSource, /environment that launches Electron/)
})

test('startup login gate hides runtime UI before auth and session choice completion', () => {
  const gateIndex = diagnosticsSource.indexOf('if (!startupAuthenticated && shouldShowStartupLogin())')
  const choiceIndex = diagnosticsSource.indexOf("if (startupAuthenticated && startupScreen === 'session-choice')")
  const setupIndex = diagnosticsSource.indexOf("if (startupAuthenticated && startupScreen === 'session-setup')")
  const runtimeIndex = diagnosticsSource.indexOf('<div className="diagnostics-scroll">')

  assert.ok(gateIndex >= 0)
  assert.ok(choiceIndex > gateIndex)
  assert.ok(setupIndex > choiceIndex)
  assert.ok(runtimeIndex > setupIndex)
  assert.match(diagnosticsSource, /<StartupLoginScreen/)
  assert.match(diagnosticsSource, /<StartupSessionChoiceScreen/)
  assert.match(diagnosticsSource, /<StartupSessionSetupScreen/)
  assert.match(diagnosticsSource, /const \[startupScreen, setStartupScreen\] = useState\('login'\)/)
  assert.match(diagnosticsSource, /const \[startupSessionConfig, setStartupSessionConfig\] = useState\(null\)/)
  assert.match(diagnosticsSource, /setStartupScreen\('session-choice'\)/)
  assert.match(
    diagnosticsSource,
    /onCreateSession={\(\) => {[\s\S]*?setStartupSessionConfig\(null\)[\s\S]*?onStartupSessionConfigChange\?\.\(null\)[\s\S]*?setStartupScreen\('session-setup'\)[\s\S]*?}}/
  )
})

test('startup session setup completion uses narrow Electron startup hook', () => {
  assert.match(preloadSource, /completeStartup: \(\) => ipcRenderer\.invoke\('startup:complete'\)/)
  assert.match(preloadSource, /listCloudResumes: \(\) => ipcRenderer\.invoke\('cloud:list-resumes'\)/)
  assert.match(preloadSource, /generateAnswer: \(body\) => ipcRenderer\.invoke\('generate:answer', body\)/)
  assert.match(preloadSource, /listCloudResumes: electronAPI\.listCloudResumes/)
  assert.match(preloadSource, /generateAnswer: electronAPI\.generateAnswer/)
  assert.match(mainSource, /ipcMain\.handle\('startup:complete'/)
  assert.match(mainSource, /ipcMain\.handle\('cloud:list-resumes', async \(event\) => {[\s\S]*?validateAuthIpc\(event\)[\s\S]*?desktopAuthSessionManager\.listCloudResumes\(\)/)
  assert.match(mainSource, /ipcMain\.handle\('generate:answer', async \(event, body\) => {[\s\S]*?validateAuthIpc\(event\)[\s\S]*?desktopAuthSessionManager\.generateAnswer\(body\)/)
  assert.match(mainSource, /validateAuthIpc\(event\)/)
  assert.match(mainSource, /desktopAuthSessionManager\.getSafeState\(\)\.status !== 'connected'/)
  assert.match(sessionSource, /async listCloudResumes\(\)/)
  assert.match(sessionSource, /this\._backendJson\('\/api\/resumes', 'GET', this\.session\.access_token\)/)
  assert.match(sessionSource, /function safeCloudResumeItem/)
  assert.doesNotMatch(startupChoiceSource, /completeStartup/)
  assert.match(startupSetupSource, /electronApi\?\.completeStartup\?\.\(\)/)
  assert.match(startupSetupSource, /const result = await electronApi\?\.completeStartup\?\.\(\)/)
  assert.match(startupSetupSource, /if \(result\?\.ok !== true\) {[\s\S]*?setMessage/)
  assert.match(startupSetupSource, /onStartSession\?\.\(\{/)
})

test('main process starts compact and keeps overlay hidden before startup completion', () => {
  const readyStart = mainSource.indexOf("app.on('ready'")
  const readyEnd = mainSource.indexOf("function validateAuthIpc")
  const readyBlock = mainSource.slice(readyStart, readyEnd)

  assert.match(mainSource, /let startupFlowComplete = false/)
  assert.match(mainSource, /let overlayVisible = false/)
  assert.match(mainSource, /width: 504,[\s\S]*?height: 462,[\s\S]*?minWidth: 426,[\s\S]*?minHeight: 384,/)
  assert.match(mainSource, /show: false,/)
  assert.doesNotMatch(readyBlock, /buildApplicationMenu\(\)[\s\S]*?createMainWindow\(\)[\s\S]*?createOverlayWindow\(\)[\s\S]*?startForegroundWindowTracking\(\)/)
  assert.match(readyBlock, /if \(startupFlowComplete && overlayWindow === null\) {[\s\S]*?createOverlayWindow\(\)/)
  assert.match(mainSource, /function createOverlayWindow\(\) {[\s\S]*?if \(!startupFlowComplete\) {[\s\S]*?return null/)
  assert.match(mainSource, /const hideOk = globalShortcut\.register\('Control\+H', \(\) => {[\s\S]*?if \(!startupFlowComplete\) {[\s\S]*?return/)
  assert.match(mainSource, /ipcMain\.handle\('overlay:toggle-visibility', \(\) => {[\s\S]*?if \(!startupFlowComplete\) {[\s\S]*?return { visible: false }/)
  assert.match(mainSource, /function completeStartupFlow\(\)[\s\S]*?mainWindow\.setSize\(620, 860\)[\s\S]*?syncOverlayVisibility\(true\)/)
})

test('main process logout resets startup flow and hides overlay before login', () => {
  assert.match(mainSource, /function resetStartupFlow\(\)[\s\S]*?startupFlowComplete = false[\s\S]*?syncOverlayVisibility\(false\)/)
  assert.match(mainSource, /function resetStartupFlow\(\)[\s\S]*?mainWindow\.setMinimumSize\(426, 384\)[\s\S]*?mainWindow\.setSize\(504, 462\)[\s\S]*?mainWindow\.show\(\)/)
  assert.match(mainSource, /ipcMain\.handle\('auth:logout', async \(event\) => {[\s\S]*?const state = await desktopAuthSessionManager\.logout\(\)[\s\S]*?if \(state\.status === 'signed-out' \|\| state\.status === 'token-expired'\) {[\s\S]*?resetStartupFlow\(\)/)
  assert.match(mainSource, /const hideOk = globalShortcut\.register\('Control\+H', \(\) => {[\s\S]*?if \(!startupFlowComplete\) {[\s\S]*?return[\s\S]*?toggleOverlayVisibility\(\)/)
  assert.match(diagnosticsSource, /setStartupAuthenticated\(false\)[\s\S]*?setStartupScreen\('login'\)[\s\S]*?setStartupSessionConfig\(null\)/)
})

test('startup login close button uses narrow validated Electron startup hook', () => {
  assert.match(startupSource, /aria-label="Close startup login"/)
  assert.match(startupSource, /const closeWindow = saiiaApi\?\.closeStartupWindow \|\| electronApi\?\.closeStartupWindow/)
  assert.match(startupSource, /closeWindow\?\.\(\)\.catch\?\.\(\(\) => {}\)/)
  assert.match(startupSource, /onClick={closeStartupWindow}/)
  assert.match(preloadSource, /closeStartupWindow: \(\) => ipcRenderer\.invoke\('startup:close'\)/)
  assert.match(preloadSource, /closeStartupWindow: electronAPI\.closeStartupWindow/)
  assert.match(mainSource, /ipcMain\.handle\('startup:close'/)
  assert.match(mainSource, /function closeStartupWindow\(\)[\s\S]*?if \(!startupFlowComplete\) {[\s\S]*?globalShortcut\.unregisterAll\(\)[\s\S]*?app\.quit\(\)/)
  assert.match(mainSource, /ipcMain\.handle\('startup:close', \(event\) => {[\s\S]*?validateAuthIpc\(event\)/)
})

test('startup login source and styles do not expose token or session values', () => {
  assert.doesNotMatch(startupSource, sensitivePattern)
  assert.doesNotMatch(startupChoiceSource, sensitivePattern)
  assert.doesNotMatch(startupSetupSource, sensitivePattern)
  assert.doesNotMatch(cssSource, sensitivePattern)
  assert.doesNotMatch(startupSource, /SUPABASE_URL|SUPABASE_ANON_KEY|SAIIA_WEB_AUTH_URL|SAIIA_DESKTOP_AUTH_PROVIDER|GOOGLE_CLIENT_SECRET/)
})

test('startup login CSS keeps Figma dimensions and visual values', () => {
  assert.match(cssSource, /\.startup-login-card\s*{[\s\S]*?width: 426px;[\s\S]*?height: 420px;/)
  assert.match(cssSource, /\.startup-login-window,[\s\S]*?\.startup-choice-window\s*{[\s\S]*?width: 504px;[\s\S]*?height: 462px;/)
  assert.match(cssSource, /\.startup-login-window\s*{[\s\S]*?align-items: center;[\s\S]*?justify-content: center;/)
  assert.match(cssSource, /\.startup-login-window\s*{[\s\S]*?box-sizing: border-box;/)
  assert.match(cssSource, /\.startup-login-card\s*{[\s\S]*?box-sizing: border-box;/)
  assert.match(cssSource, /\.startup-login-header\s*{[\s\S]*?width: 426px;[\s\S]*?height: 48px;[\s\S]*?border-bottom: 1px solid rgba\(197, 198, 205, 0\.2\);/)
  assert.match(cssSource, /\.startup-login-main\s*{[\s\S]*?width: 360px;[\s\S]*?gap: 18px;/)
  assert.match(cssSource, /\.startup-login-button\s*{[\s\S]*?width: 320px;[\s\S]*?height: 54px;[\s\S]*?background: #0058be;/)
  assert.match(cssSource, /font-family: Inter/)
  assert.match(cssSource, /#0058be/i)
  assert.match(cssSource, /#667085/i)
  assert.match(cssSource, /#091426/i)
  assert.match(cssSource, /\.startup-login-close path\s*{[\s\S]*?stroke: currentcolor;/)
})

test('startup session choice screen matches Figma shell and safe placeholder behavior', () => {
  assert.match(startupChoiceSource, /Start a New Session/)
  assert.match(startupChoiceSource, /Choose how you'd like to continue\./)
  assert.match(startupChoiceSource, /Free Session/)
  assert.match(startupChoiceSource, /10 minutes available/)
  assert.match(startupChoiceSource, /Create New Session/)
  assert.match(startupChoiceSource, /Buy Credits/)
  assert.match(startupChoiceSource, /Past sessions will be available in a later phase\./)
  assert.match(startupChoiceSource, /aria-label="Intervu AI startup session choices"/)
  assert.match(startupChoiceSource, /aria-label="10 of 10 minutes remaining"/)
  assert.match(cssSource, /\.startup-choice-card\s*{[\s\S]*?width: 504px;[\s\S]*?height: 462px;/)
  assert.match(cssSource, /\.startup-choice-header\s*{[\s\S]*?height: 65px;/)
  assert.match(cssSource, /\.startup-choice-tabs\s*{[\s\S]*?width: 456px;[\s\S]*?height: 50px;/)
  assert.match(cssSource, /\.startup-choice-option\s*{[\s\S]*?height: 140px;[\s\S]*?border-radius: 16px;/)
  assert.match(cssSource, /\.startup-choice-footer\s*{[\s\S]*?width: 456px;[\s\S]*?height: 46px;/)
})

test('startup session setup screen collects local setup and routes back or into runtime', () => {
  assert.match(startupSetupSource, /const EMPTY_SETUP = {[\s\S]*?title: ''[\s\S]*?role: ''[\s\S]*?company: ''[\s\S]*?jobContext: ''[\s\S]*?selectedResumeId: ''[\s\S]*?selectedResumeName: ''/)
  assert.match(startupSetupSource, /Session title/)
  assert.match(startupSetupSource, /Target role/)
  assert.match(startupSetupSource, /Company name/)
  assert.match(startupSetupSource, /Job description \/ context/)
  assert.match(startupSetupSource, /Resume \/ reference document/)
  assert.match(startupSetupSource, /saiiaApi\.listCloudResumes/)
  assert.match(startupSetupSource, /Loading resumes\.\.\./)
  assert.match(startupSetupSource, /No uploaded resumes found\. Upload a resume from the web dashboard first\./)
  assert.match(startupSetupSource, /Open dashboard to upload resume/)
  assert.match(startupSetupSource, /const READINESS_LABELS = {[\s\S]*?ready: 'Ready'[\s\S]*?processing: 'Processing'[\s\S]*?not_indexed: 'Needs indexing'[\s\S]*?needs_confirmation: 'Needs confirmation'[\s\S]*?failed: 'Failed'/)
  assert.match(startupSetupSource, /getResumeReadinessLabel\(resume\)/)
  assert.match(startupSetupSource, /value={draft\.selectedResumeId}/)
  assert.match(startupSetupSource, /selectedResumeName: selected\?\.display_name \|\| ''/)
  assert.match(startupSetupSource, /const selectedResumeBlocked = Boolean\(\s*draft\.selectedResumeId && \(resumesLoading \|\| !selectedResume \|\| selectedResume\.can_generate !== true\)\s*\)/)
  assert.match(startupSetupSource, /Loading the latest resume readiness before starting your session\./)
  assert.match(startupSetupSource, /Finish extraction\/indexing from the dashboard, then refresh\./)
  assert.match(startupSetupSource, /Open dashboard to finish resume setup/)
  assert.match(startupSetupSource, /disabled={starting \|\| selectedResumeBlocked}/)
  assert.match(startupSetupSource, /onBack/)
  assert.match(startupSetupSource, /Start Session/)
  assert.match(startupSetupSource, /sessionTitle: draft\.title/)
  assert.match(startupSetupSource, /targetRole: draft\.role/)
  assert.match(startupSetupSource, /companyName: draft\.company/)
  assert.match(startupSetupSource, /jobDescription: draft\.jobContext/)
  assert.match(diagnosticsSource, /onBack={\(\) => setStartupScreen\('session-choice'\)}/)
  assert.match(diagnosticsSource, /setStartupSessionConfig\(nextConfig\)[\s\S]*?setStartupScreen\('runtime'\)/)
  assert.match(diagnosticsSource, /onStartupSessionConfigChange\?\.\(nextConfig\)/)
  assert.match(diagnosticsSource, /onStartupSessionConfigChange\?\.\(null\)/)
  assert.match(appSource, /const \[startupSessionConfig, setStartupSessionConfig\] = useState\(null\)/)
  assert.match(appSource, /const startupSessionConfigRef = useRef\(null\)/)
  assert.match(appSource, /const applyStartupSessionConfig = \(nextConfig\) => {[\s\S]*?startupSessionConfigRef\.current = nextConfig[\s\S]*?setStartupSessionConfig\(nextConfig\)[\s\S]*?}/)
  assert.match(appSource, /onStartupSessionConfigChange={applyStartupSessionConfig}/)
  assert.match(appSource, /const activeStartupSessionConfig = startupSessionConfigRef\.current/)
  assert.match(appSource, /const selectedResumeId = String\(activeStartupSessionConfig\?\.selectedResumeId \|\| ''\)\.trim\(\)/)
  assert.match(appSource, /const selectedResumeName = String\(activeStartupSessionConfig\?\.selectedResumeName \|\| ''\)\.trim\(\)/)
  assert.match(appSource, /activeStartupSessionConfig\?\.targetRole \|\| activeStartupSessionConfig\?\.role/)
  assert.match(appSource, /activeStartupSessionConfig\?\.companyName \|\| activeStartupSessionConfig\?\.company/)
  assert.match(appSource, /activeStartupSessionConfig\?\.jobDescription \|\| activeStartupSessionConfig\?\.jobContext/)
  assert.match(appSource, /profile: selectedResumeId \? \{\} : liveProfile/)
  assert.match(appSource, /selected_resume_id: selectedResumeId \|\| undefined/)
  assert.match(appSource, /target_role: targetRole \|\| undefined/)
  assert.match(appSource, /company_name: companyName \|\| undefined/)
  assert.match(appSource, /job_description: jobDescription \|\| undefined/)
  assert.match(appSource, /window\.saiia\?\.generateAnswer/)
  assert.match(appSource, /Intervu AI selected resume generation diagnostics/)
  assert.match(appSource, /generationRequestIncludesSelectedResumeId: Boolean\(generateRequestBody\.selected_resume_id\)/)
  const selectedResumeDiagnosticsBlock =
    appSource.match(/const selectedResumeDiagnostics = \{[\s\S]*?\n    \}/)?.[0] || ''
  assert.ok(selectedResumeDiagnosticsBlock, 'selectedResumeDiagnostics block should exist')
  assert.doesNotMatch(selectedResumeDiagnosticsBlock, /selectedResumeName/)
  assert.match(appSource, /Selected resume is not ready for generation\. Please finish resume setup or rebuild the index from the dashboard\./)
  assert.match(appSource, /Selected resume is not ready or does not contain enough project context for this answer\./)
  assert.match(appSource, /resume_context_source: generatePayload\.resume_context_source \|\| 'none'/)
  assert.match(appSource, /selected_resume_id_used: generatePayload\.selected_resume_id_used \?\? false/)
  assert.match(appSource, /selected_resume_chunk_count: generatePayload\.selected_resume_chunk_count \?\? 0/)
  assert.match(appSource, /selected_resume_candidate_name_available:[\s\S]*?generatePayload\.selected_resume_candidate_name_available \?\? false/)
  assert.match(appSource, /selected_resume_candidate_name_source: generatePayload\.selected_resume_candidate_name_source \|\| 'none'/)
  assert.match(appSource, /selected_resume_strict_mode: generatePayload\.selected_resume_strict_mode \?\? false/)
  assert.match(appSource, /selected_resume_context_used_in_prompt: generatePayload\.selected_resume_context_used_in_prompt \?\? false/)
  assert.match(appSource, /generic_fallback_blocked: generatePayload\.generic_fallback_blocked \?\? false/)
  assert.match(appSource, /profile_fallback_blocked: generatePayload\.profile_fallback_blocked \?\? false/)
  assert.match(appSource, /profile_context_suppressed_by_selected_resume:[\s\S]*?generatePayload\.profile_context_suppressed_by_selected_resume \?\? false/)
  assert.match(appSource, /final_context_priority: generatePayload\.final_context_priority \|\| 'none'/)
  assert.match(appSource, /job_context_included: generatePayload\.job_context_included \?\? Boolean\(companyName \|\| jobDescription\)/)
  assert.match(appSource, /target_role_included: generatePayload\.target_role_included \?\? Boolean\(targetRole\)/)
  assert.match(appSource, /project_intent_detected: generatePayload\.project_intent_detected \?\? false/)
  assert.match(appSource, /generationRequestIncludesSelectedResumeId: Boolean\(generateRequestBody\.selected_resume_id\)/)
  assert.match(appSource, /jobContextIncluded: Boolean\(companyName \|\| jobDescription\)/)
  assert.match(appSource, /targetRoleIncluded: Boolean\(targetRole\)/)
  assert.match(diagnosticsSource, /label="Context priority"/)
  assert.match(diagnosticsSource, /label="Job context request"/)
  assert.match(diagnosticsSource, /label="Target role request"/)
  assert.match(diagnosticsSource, /label="Job context in prompt"/)
  assert.match(diagnosticsSource, /label="Target role in prompt"/)
  assert.match(diagnosticsSource, /label="Project intent"/)
  assert.match(diagnosticsSource, /label="Selected resume strict"/)
  assert.match(diagnosticsSource, /label="Selected context in prompt"/)
  assert.match(diagnosticsSource, /label="Generic fallback blocked"/)
  assert.match(diagnosticsSource, /label="Profile fallback blocked"/)
  assert.match(diagnosticsSource, /label="Old profile suppressed"/)
  assert.match(diagnosticsSource, /label="Selected resume name"/)
  assert.match(diagnosticsSource, /label="Selected name source"/)
  assert.match(appSource, /selectedResumeIdExists: Boolean\(String\(startupSessionConfig\?\.selectedResumeId \|\| ''\)\.trim\(\)\)/)
  assert.match(diagnosticsSource, /label="Resume context source"/)
  assert.match(diagnosticsSource, /label="Selected resume request"/)
  assert.match(appSource, /applyStartupSessionConfig\(null\)/)
  assert.match(cssSource, /\.startup-setup-card\s*{[\s\S]*?width: 504px;[\s\S]*?height: 462px;/)
  assert.match(cssSource, /\.startup-setup-main\s*{[\s\S]*?overflow-y: auto;/)
})

test('startup login keeps long configuration errors in a bounded message area', () => {
  assert.match(startupSource, /const errorDetail = authState\.error \|\| ''/)
  assert.match(startupSource, /const errorText = getStartupErrorMessage\(errorDetail\)/)
  assert.match(startupSource, /className={`startup-login-main\$\{errorText \? ' startup-login-main--error' : ''\}`}/)
  assert.match(startupSource, /<p className="startup-login-error" aria-live="polite" title={errorDetail}>/)
  assert.match(startupSource, /return 'Desktop auth is not configured\.'/)
  assert.match(cssSource, /\.startup-login-error\s*{[\s\S]*?position: absolute;[\s\S]*?top: 160px;[\s\S]*?height: 14px;[\s\S]*?overflow: hidden;[\s\S]*?font-size: 10px;/)
  assert.doesNotMatch(cssSource, /\.startup-login-main--error \.startup-login-features\s*{[\s\S]*?height: 54px;/)
})
